name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cp /home/repositories/mx-sports/mx-sports-backend/.env /root/actions-runner/mx-sports/mx-sports-backend/mx-sports-backend/.env
    - run: npm i
    - run: npm run build
    - run: pm2 restart mx-sports
